# Generated by Django 6.0.2 on 2026-04-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_number',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
